export const artists = [
  {
    "id": 1,
    "name": "Luca",
    "lastname": "Martini",
    "address": "Calle 123",
    "biography": "Luca Martini nació en Buenos Aires, Argentina, y creció rodeado de un entorno creativo e industrial. Desde niño estuvo influenciado por la tradición familiar en el trabajo con materiales como madera, plásticos y metales, un legado que abarcaba desde lo artesanal hasta lo empresarial. Con 29 años, Luca ha logrado integrar esta rica herencia con su pasión por el diseño y el arte, dando vida a obras únicas que combinan precisión técnica y sensibilidad artística. Aunque siempre estuvo en contacto con el arte a través del dibujo, fue su abuela quien lo inspiró a explorar su creatividad desde pequeño, un acto que recuerda con especial gratitud. Formalmente, su incursión en el arte comenzó hace dos años, evolucionando desde sus estudios en diseño industrial y arquitectura, y su experiencia profesional en la industria aeroespacial. En sus obras, Luca utiliza una amplia gama de materiales y técnicas como madera, melaminas, MDF, hormigón, vidrio y acrílico, integrando tecnología con un enfoque artesanal que busca un balance entre lo cálido y lo preciso. Temáticamente, su trabajo se inspira en la geometría sagrada, patrones naturales, el cosmos y la biomímesis, explorando una estética orgánica y abstracta que invita al observador a sumergirse en detalles infinitos. Luca considera el arte como una narrativa visual que condensa información y movimiento. Sus piezas suelen incorporar retroiluminación, generando efectos lumínicos que evocan conexiones espirituales y cósmicas. La espiritualidad y la naturaleza son pilares en su proceso creativo, influenciado por culturas védicas, el arte precolombino y movimientos como el Art Nouveau. Entre los momentos clave de su trayectoria destacan sus primeras pruebas artísticas, que marcaron la unión entre su mirada industrial y la artística, así como sus exposiciones en MBL, la Feria Puro Diseño y un evento arquitectónico donde recibió comentarios significativos. Su estudio, llamado 108, rinde homenaje a la conexión espiritual entre lo físico y lo etéreo, reflejando su interés por la astronomía, los patrones naturales y las expresiones artísticas que trascienden lo tangible. Cuando no está creando, Luca disfruta del automovilismo, el cine, la enseñanza del diseño industrial y, sobre todo, de compartir momentos con su familia y amigos. Sus mejores ideas suelen surgir en estos momentos de relajación. Como consejo para jóvenes artistas, enfatiza la importancia de ser auténticos, experimentar sin miedo y abrazar los errores como oportunidades para alcanzar grandeza.",
    "dateOfBirth": "1995-01-01",
    "technique": "Medios Mixtos",
    "nationality": "Argentina",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1734699703/galarte/artists/luca-martini-artist-image.jpg",
    "documentType": "",
    "document": "",
    "createdAt": "2024-12-20 13:01:45",
    "updatedAt": "2024-12-20 13:01:45"
  },
  {
    "id": 2,
    "name": "Eva",
    "lastname": "Saevich",
    "address": "Calle 123",
    "biography": "Eva nació en Buenos Aires y, desde pequeña, encontró en el arte un refugio y una forma de expresión única. Su trabajo, hecho completamente a mano, utiliza técnicas de papercut y collage, transformando papel en figuras y texturas inspiradas en la naturaleza.\nCon una vida marcada por desafíos visuales, Eva ha adaptado su arte a sus posibilidades, desarrollando un estilo preciso y armonioso que le permite trabajar de cerca, conectándose profundamente con sus materiales.\nHoy vive rodeada de naturaleza, lejos del ruido de la ciudad, donde encuentra inspiración en los paisajes, los sonidos y la música. Sus piezas han viajado por Argentina, Bélgica, España y México, llevando su sensibilidad y conexión con lo esencial a nuevas miradas.\nEva transforma el papel en historias y emociones, creando obras que invitan a contemplar la belleza del mundo natural.",
    "dateOfBirth": "1978-03-03",
    "technique": "Paper Cut",
    "nationality": "Argentina",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1734715823/galarte/artists/eva-saevich-artist-imagen.jpg",
    "documentType": "",
    "document": "",
    "createdAt": "2024-12-20 13:18:07",
    "updatedAt": "2024-12-20 13:18:07"
  },
  {
    "id": 3,
    "name": "Flora",
    "lastname": "Kai",
    "address": "Calle 123",
    "biography": "Flora Kai es una ceramista y artista multidisciplinaria nacida en La Plata y criada en Chile, cuya obra explora la psicodelia de la naturaleza, la magia y el viaje físico y espiritual. Con un estilo que ella describe como \"groovy, cute y un poco punk\", Flora combina técnicas escultóricas e instalativas, creando piezas únicas que conectan lo ancestral con lo contemporáneo.",
    "dateOfBirth": "1994-01-01",
    "technique": "Ceramista",
    "nationality": "Argentina",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1737504092/galarte/artists/flora-kai-artist-image.jpg",
    "documentType": "",
    "document": "",
    "createdAt": "2024-12-20 13:24:21",
    "updatedAt": "2024-12-20 13:24:21"
  },
  {
    "id": 4,
    "name": "Juana",
    "lastname": "Marlla",
    "address": "Calle 123",
    "biography": "Ornella Migliori ha explorado el dibujo y la pintura desde que tiene memoria. Diseñadora gráfica por la FADU, su formación le ha brindado herramientas que enriquecen su búsqueda artística, centrada actualmente en el óleo. Su obra, de estilo surrealista y kitsch, aborda la fragilidad humana, lo grotesco y el límite entre lo real y lo imaginario.\nInspirada por artistas como Marcia Schvartz, Marcos López y Nicola Constantino, Ornella crea composiciones intensas, imperfectas y cargadas de color. Su lema: “más está bien”.\nCuando no está creando, encuentra calma y conexión con su perra, su cable a tierra en el bullicio cotidiano.",
    "dateOfBirth": "1996-01-01",
    "technique": "Pintura",
    "nationality": "Argentina",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1737504263/galarte/artists/juana-marlla-artist-image.jpg",
    "documentType": "",
    "document": "",
    "createdAt": "2024-12-20 17:31:59",
    "updatedAt": "2024-12-20 17:31:59"
  },
  {
    "id": 5,
    "name": "Alejandro",
    "lastname": "Casas",
    "address": "Calle 123",
    "biography": "Texto de ejemplo",
    "dateOfBirth": "2000-01-01",
    "technique": "Pintura",
    "nationality": "Colombia",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1737504126/galarte/artists/alejandro-casas-artist-image.jpg",
    "documentType": "",
    "document": "",
    "createdAt": "2024-12-20 17:35:10",
    "updatedAt": "2024-12-20 17:35:10"
  },
  {
    "id": 6,
    "name": "Nahuel",
    "lastname": "Griuffrida",
    "address": "Calle 123",
    "biography": "Nacido en Buenos Aires en 1986, Nahuel Giuffrida es un artista autodidacta que explora la geometría, el color y la pureza de las formas. Su obra combina diversas técnicas y materiales como cerámica, pintura, fotografía analógica y collage, influenciada por movimientos como el Futurismo italiano, el Surrealismo francés y la Vanguardia rusa. Ha participado en múltiples exposiciones y en 2024 formó parte de ArteBA junto a Popa Galería. Reside en Ramos Mejía, donde mantiene un hogar-taller que refleja su conexión entre arte y naturaleza.",
    "dateOfBirth": "1986-01-01",
    "technique": "Cerámica \nFotografía analógica \nPintura ( óleo , acrílico , aerosol)\nLapicera bolígrafo \nMaderas\nPapeles para collage",
    "nationality": "Argentina",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1737504197/galarte/artists/nahuel-griuffrida-artist-image.jpg",
    "documentType": "",
    "document": "",
    "createdAt": "2025-01-10 23:50:30",
    "updatedAt": "2025-01-10 23:50:30"
  },
  {
    "id": 7,
    "name": "Gustavo",
    "lastname": "Sanchez",
    "address": "Calle 123",
    "biography": "Nacido en Caracas y radicado en Buenos Aires desde 2016, Gustavo Sánchez es fotógrafo de paisajes y escenas urbanas. Comenzó a los 23 años explorando la luz con una cámara prestada, y desde entonces ha desarrollado un estilo que combina panorámicas naturales —especialmente de la Patagonia y el norte argentino— con fotografía callejera en blanco y negro. Formado en Foto Arte (Caracas y Buenos Aires) y en talleres internacionales del MoMA, su obra está influenciada por Ansel Adams y se imprime en papeles Fine Art o fotográficos de alta calidad. Ha recibido menciones en concursos como Monovisions Awards y el del Automóvil Club Argentino, y ha expuesto en espacios como Calypso Café, Antiguas Lunas y la Feria de Fotografía. Actualmente, también experimenta con paste up en el espacio público, combinando arte y calle en nuevos formatos.",
    "dateOfBirth": "1983-01-01",
    "technique": "Fotografía digital",
    "nationality": "Venezuela",
    "image": "https://res.cloudinary.com/durmcbjkd/image/upload/v1746751310/gustavoSanchez_dkdf1m.jpg",
    "documentType": "",
    "document": "",
    "createdAt": "2025-05-08 20:35:30",
    "updatedAt": "2025-05-08 20:35:30"
  }
]

export const artworks = [
  {
    "id": 1,
    "name": "BLACK PUNK MUG",
    "description": "Tazón negro de cerámica con pinches modelada y esmalta. Posee un efecto iridiscente producto de técnicas de tercer fuego.",
    "code": "1",
    "serialNumber": "1",
    "width": 7,
    "height": 12,
    "technique": "Cerámica",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736554617/galarte/artworks/BLACK%20PUNK%20MUG-artwork-image.jpg",
    "artistId": 3,
    "created_at": "2025-01-11 00:18:56",
    "updated_at": "2025-01-11 00:18:56",
    "price": 325,
    "isUnique": 1
  },
  {
    "id": 2,
    "name": "FANTASY VASE",
    "description": "Jarrón escultórico de cerámica modelado y esmaltado con detalles en esmalte mate y técnica de tercer fuego lo que le da los tonos iridiscentes sobre su superficie.",
    "code": "2",
    "serialNumber": "1",
    "width": 20,
    "height": 20,
    "technique": "Cerámica",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736554860/galarte/artworks/FANTASY%20VASE-artwork-image.jpg",
    "artistId": 3,
    "created_at": "2025-01-11 00:21:01",
    "updated_at": "2025-01-11 00:21:01",
    "price": 325,
    "isUnique": 1
  },
  {
    "id": 3,
    "name": "MAGIC CALYX",
    "description": "Cáliz escultórico de cerámica modelado y esmaltado con detalles perlados e iridiscentes producto de técnicas de tercer fuego aplicadas sobre su superficie.",
    "code": "3",
    "serialNumber": "1",
    "width": 18,
    "height": 10,
    "technique": "Cerámica",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736554914/galarte/artworks/MAGIC%20CALYX-artwork-image.jpg",
    "artistId": 3,
    "created_at": "2025-01-11 00:21:55",
    "updated_at": "2025-01-11 00:21:55",
    "price": 325,
    "isUnique": 1
  },
  {
    "id": 4,
    "name": "OCEAN MUG",
    "description": "Taza de cerámica modelada a mano esmaltada en azul con detalles de cristales.",
    "code": "4",
    "serialNumber": "1",
    "width": 7,
    "height": 10,
    "technique": "Cerámica",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736554970/galarte/artworks/OCEAN%20MUG-artwork-image.jpg",
    "artistId": 3,
    "created_at": "2025-01-11 00:22:51",
    "updated_at": "2025-01-11 00:22:51",
    "price": 130,
    "isUnique": 1
  },
  {
    "id": 5,
    "name": "DRAGON MUG",
    "description": "Taza de cerámica modelada a mano esmaltada en verde con detalles iridiscentes producto de técnicas de tercer fuego.",
    "code": "5",
    "serialNumber": "1",
    "width": 7,
    "height": 10,
    "technique": "Cerámica",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736554991/galarte/artworks/DRAGON%20MUG-artwork-image.jpg",
    "artistId": 3,
    "created_at": "2025-01-11 00:23:30",
    "updated_at": "2025-01-11 00:23:30",
    "price": 130,
    "isUnique": 1
  },
  {
    "id": 6,
    "name": "LILAC MUG",
    "description": "Taza de cerámica modelada a mano esmaltada con negro con detalles iridiscentes producto de técnicas de tercer fuego.",
    "code": "6",
    "serialNumber": "1",
    "width": 7,
    "height": 10,
    "technique": "Cerámica",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736555102/galarte/artworks/LILAC%20MUG-artwork-image.jpg",
    "artistId": 3,
    "created_at": "2025-01-11 00:25:03",
    "updated_at": "2025-01-11 00:25:03",
    "price": 130,
    "isUnique": 1
  },
  {
    "id": 7,
    "name": "CORAL KAI",
    "description": "Cerámica modelada y esmaltada en tonos violáceos jaspeados",
    "code": "7",
    "serialNumber": "1",
    "width": 20,
    "height": 20,
    "technique": "Cerámica",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736555135/galarte/artworks/CORAL%20KAI-artwork-image.jpg",
    "artistId": 3,
    "created_at": "2025-01-11 00:25:36",
    "updated_at": "2025-01-11 00:25:36",
    "price": 390,
    "isUnique": 1
  },
  {
    "id": 8,
    "name": "108 36",
    "description": "",
    "code": "1",
    "serialNumber": "1",
    "width": 137,
    "height": 187,
    "technique": "Pantografo cnc.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736555431/galarte/artworks/108%2036-artwork-image.jpg",
    "artistId": 1,
    "created_at": "2025-01-11 00:30:32",
    "updated_at": "2025-01-11 00:30:32",
    "price": 3250,
    "isUnique": 1
  },
  {
    "id": 10,
    "name": "108 16",
    "description": "",
    "code": "2",
    "serialNumber": "1",
    "width": 85,
    "height": 108,
    "technique": "Pantografo cnc.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736555745/galarte/artworks/108%2016-artwork-image.jpg",
    "artistId": 1,
    "created_at": "2025-01-11 00:35:46",
    "updated_at": "2025-01-11 00:35:46",
    "price": 2015,
    "isUnique": 1
  },
  {
    "id": 11,
    "name": "108 A27",
    "description": "",
    "code": "3",
    "serialNumber": "1",
    "width": 60,
    "height": 275,
    "technique": "Pantografo cnc.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736556042/galarte/artworks/108%20A27-artwork-image.jpg",
    "artistId": 1,
    "created_at": "2025-01-11 00:40:43",
    "updated_at": "2025-01-11 00:40:43",
    "price": 2860,
    "isUnique": 1
  },
  {
    "id": 12,
    "name": "108 30",
    "description": "",
    "code": "4",
    "serialNumber": "1",
    "width": 135,
    "height": 187,
    "technique": "Pantografo cnc.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736556080/galarte/artworks/108%2030-artwork-image.jpg",
    "artistId": 1,
    "created_at": "2025-01-11 00:41:20",
    "updated_at": "2025-01-11 00:41:20",
    "price": 3510,
    "isUnique": 1
  },
  {
    "id": 13,
    "name": "Serie \"La Naturaleza del Amor\"",
    "description": "",
    "code": "1",
    "serialNumber": "1",
    "width": 50,
    "height": 60,
    "technique": "Paper cut.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1740944075/galarte/artworks/IMG_0610_ocjntc.jpg",
    "artistId": 2,
    "created_at": "2025-01-11 00:45:08",
    "updated_at": "2025-01-11 00:45:08",
    "price": 600,
    "isUnique": 1
  },
  {
    "id": 14,
    "name": "Serie \"La Naturaleza del Amor\"",
    "description": "",
    "code": "2",
    "serialNumber": "1",
    "width": 33,
    "height": 50,
    "technique": "Paper cut.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736556343/galarte/artworks/Serie%20%22La%20Naturaleza%20del%20Amor%22-artwork-image.jpg",
    "artistId": 2,
    "created_at": "2025-01-11 00:46:00",
    "updated_at": "2025-01-11 00:46:00",
    "price": 400,
    "isUnique": 1
  },
  {
    "id": 15,
    "name": "Serie \"Seres\"",
    "description": "",
    "code": "3",
    "serialNumber": "1",
    "width": 20,
    "height": 30,
    "technique": "Paper cut.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1740944344/galarte/artworks/IMG_0606_zt1yyq.jpg",
    "artistId": 2,
    "created_at": "2025-01-11 00:46:45",
    "updated_at": "2025-01-11 00:46:45",
    "price": 280,
    "isUnique": 1
  },
  {
    "id": 16,
    "name": "Serie \"Seres\"",
    "description": "",
    "code": "4",
    "serialNumber": "1",
    "width": 20,
    "height": 30,
    "technique": "Paper cut.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1740944405/galarte/artworks/IMG_0605_wixv4j.jpg",
    "artistId": 2,
    "created_at": "2025-01-11 00:47:30",
    "updated_at": "2025-01-11 00:47:30",
    "price": 280,
    "isUnique": 1
  },
  {
    "id": 17,
    "name": "Serie \"Seres\"",
    "description": "",
    "code": "5",
    "serialNumber": "1",
    "width": 20,
    "height": 30,
    "technique": "Paper cut.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1740944432/galarte/artworks/IMG_0600_j2mggl.jpg",
    "artistId": 2,
    "created_at": "2025-01-11 00:47:52",
    "updated_at": "2025-01-11 00:47:52",
    "price": 280,
    "isUnique": 1
  },
  {
    "id": 18,
    "name": "Serie \"Seres\"",
    "description": "",
    "code": "6",
    "serialNumber": "1",
    "width": 20,
    "height": 30,
    "technique": "Paper cut.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1740944457/galarte/artworks/IMG_0599_sj4sgq.jpg",
    "artistId": 2,
    "created_at": "2025-01-11 00:48:11",
    "updated_at": "2025-01-11 00:48:11",
    "price": 280,
    "isUnique": 1
  },
  {
    "id": 19,
    "name": "Serie \"Seres\"",
    "description": "",
    "code": "7",
    "serialNumber": "1",
    "width": 20,
    "height": 30,
    "technique": "Paper cut.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1740944485/galarte/artworks/IMG_0598_r2ljvf.jpg",
    "artistId": 2,
    "created_at": "2025-01-11 00:48:31",
    "updated_at": "2025-01-11 00:48:31",
    "price": 280,
    "isUnique": 1
  },
  {
    "id": 20,
    "name": "Serie \"Seres\"",
    "description": "",
    "code": "8",
    "serialNumber": "1",
    "width": 100,
    "height": 80,
    "technique": "Paper cut.",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736556548/galarte/artworks/Serie%20%22Seres%22-artwork-image.jpg",
    "artistId": 2,
    "created_at": "2025-01-11 00:49:09",
    "updated_at": "2025-01-11 00:49:09",
    "price": 2200,
    "isUnique": 1
  },
  {
    "id": 21,
    "name": "Un baño propio",
    "description": "",
    "code": "1",
    "serialNumber": "1",
    "width": 19,
    "height": 14,
    "technique": "Óleo sobre papel",
    "framed": 0,
    "year": "2020",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736556673/galarte/artworks/Un%20ba%C3%B1o%20propio-artwork-image.jpg",
    "artistId": 5,
    "created_at": "2025-01-11 00:51:14",
    "updated_at": "2025-01-11 00:51:14",
    "price": 175,
    "isUnique": 1
  },
  {
    "id": 22,
    "name": "Eli's cafe",
    "description": "",
    "code": "2",
    "serialNumber": "1",
    "width": 18,
    "height": 18,
    "technique": "Óleo sobre papel",
    "framed": 0,
    "year": "2023",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736556704/galarte/artworks/Eli%27s%20cafe%20-artwork-image.jpg",
    "artistId": 5,
    "created_at": "2025-01-11 00:51:44",
    "updated_at": "2025-01-11 00:51:44",
    "price": 169,
    "isUnique": 1
  },
  {
    "id": 23,
    "name": "La siesta",
    "description": "",
    "code": "3",
    "serialNumber": "1",
    "width": 30,
    "height": 20,
    "technique": "Óleo sobre papel",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736556753/galarte/artworks/La%20siesta-artwork-image.jpg",
    "artistId": 5,
    "created_at": "2025-01-11 00:52:34",
    "updated_at": "2025-01-11 00:52:34",
    "price": 110,
    "isUnique": 1
  },
  {
    "id": 24,
    "name": "Naturaleza muerta en la calle",
    "description": "",
    "code": "4",
    "serialNumber": "1",
    "width": 30,
    "height": 20,
    "technique": "Óleo sobre papel",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736556798/galarte/artworks/Naturaleza%20muerta%20en%20la%20calle-artwork-image.jpg",
    "artistId": 5,
    "created_at": "2025-01-11 00:53:19",
    "updated_at": "2025-01-11 00:53:19",
    "price": 463,
    "isUnique": 1
  },
  {
    "id": 25,
    "name": "Cortauñas",
    "description": "",
    "code": "5",
    "serialNumber": "1",
    "width": 20,
    "height": 25,
    "technique": "Óleo sobre papel",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736556896/galarte/artworks/Cortau%C3%B1as-artwork-image.jpg",
    "artistId": 5,
    "created_at": "2025-01-11 00:54:57",
    "updated_at": "2025-01-11 00:54:57",
    "price": 46,
    "isUnique": 1
  },
  {
    "id": 26,
    "name": "Madre",
    "description": "",
    "code": "1",
    "serialNumber": "1",
    "width": 40,
    "height": 50,
    "technique": "Óleo sobre papel",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736557115/galarte/artworks/Madre-artwork-image.jpg",
    "artistId": 4,
    "created_at": "2025-01-11 00:58:36",
    "updated_at": "2025-01-11 00:58:36",
    "price": 520,
    "isUnique": 1
  },
  {
    "id": 27,
    "name": "Decapitada",
    "description": "",
    "code": "2",
    "serialNumber": "1",
    "width": 45,
    "height": 30,
    "technique": "Óleo sobre papel",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736557148/galarte/artworks/Decapitada-artwork-image.jpg",
    "artistId": 4,
    "created_at": "2025-01-11 00:59:09",
    "updated_at": "2025-01-11 00:59:09",
    "price": 390,
    "isUnique": 1
  },
  {
    "id": 28,
    "name": "Colgada",
    "description": "",
    "code": "3",
    "serialNumber": "1",
    "width": 30,
    "height": 35,
    "technique": "Óleo sobre papel",
    "framed": 0,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736557169/galarte/artworks/Colgada-artwork-image.jpg",
    "artistId": 4,
    "created_at": "2025-01-11 00:59:30",
    "updated_at": "2025-01-11 00:59:30",
    "price": 325,
    "isUnique": 1
  },
  {
    "id": 29,
    "name": "Cuadrado",
    "description": "",
    "code": "1",
    "serialNumber": "1",
    "width": 21,
    "height": 21,
    "technique": "Pintura acrílico sobre madera",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736557293/galarte/artworks/Cuadrado-artwork-image.jpg",
    "artistId": 6,
    "created_at": "2025-01-11 01:01:34",
    "updated_at": "2025-01-11 01:01:34",
    "price": 520,
    "isUnique": 1
  },
  {
    "id": 30,
    "name": "Trapecio irregular",
    "description": "",
    "code": "2",
    "serialNumber": "1",
    "width": 21,
    "height": 21,
    "technique": "Cerigrafia y lapicero",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/dsn6sloki/image/upload/v1736557315/galarte/artworks/Trapecio%20irregular-artwork-image.jpg",
    "artistId": 6,
    "created_at": "2025-01-11 01:01:56",
    "updated_at": "2025-01-11 01:01:56",
    "price": 1040,
    "isUnique": 1
  },
  {
    "id": 31,
    "name": "Estancia La Chica",
    "description": "",
    "code": "2",
    "serialNumber": "1",
    "width": 100,
    "height": 24,
    "technique": "Papel luster (fotografico) Satin pro 260g",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/durmcbjkd/image/upload/v1746754103/IMG_0566_ip1pej.png",
    "artistId": 7,
    "created_at": "2025-05-08 20:35:30",
    "updated_at": "2025-05-08 20:35:30",
    "price": 195,
    "isUnique": 1
  },
  {
    "id": 32,
    "name": "Laguna Jakob",
    "description": "",
    "code": "2",
    "serialNumber": "1",
    "width": 100,
    "height": 36,
    "technique": "Papel luster (fotografico) Satin pro 260g",
    "framed": 1,
    "year": "2024",
    "image": "https://res.cloudinary.com/durmcbjkd/image/upload/v1746754102/IMG_0562_r2xfp3.png",
    "artistId": 7,
    "created_at": "2025-05-08 20:35:30",
    "updated_at": "2025-05-08 20:35:30",
    "price": 195,
    "isUnique": 1
  }
]
